package com.renjun.vo;

import java.util.Date;

public class yw_RightInformation {
  
    private Integer rightinformationid;

  
    private Integer parcelunitid;

  
    private Date startingtime;	

   
    private Date endtime;

   
    private String obtainprice;

  
    private String landuserights;

    
    private Integer certificateboardid;

   
    private Integer characteristicmethodid;

   
    private String registrationreason;

  
    private String excursus;

    //新增字段
    private String warrantnumber;
    private String commonwayname;
    private String sit;
    private String realrstateunitnumber;
    private String typeofrightname;
    private String processclassificationname;
    private String usename;
    private String parcelcode;
    private String parcelarea;
    
    private String userightarea;
    private String highbuildinglimit;
    private String buildingdensity;
    private String plotratio;
    private String parcelconditioncode;
    private String mapnumber;
    private Integer boxofficeid;
    private String enddata;
  
    private String zsbhnumber;
    
    private String identifier;
      
    private String certificateboardname;
    private String characteristicmethodname;
    public String getEnddata() {
		return enddata;
	}

	public void setEnddata(String enddata) {
		this.enddata = enddata;
	}

	public Integer getRightinformationid() {
        return rightinformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.rightInformationId
     *
     * @param rightinformationid the value for yw_rightinformation.rightInformationId
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setRightinformationid(Integer rightinformationid) {
        this.rightinformationid = rightinformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.parcelUnitId
     *
     * @return the value of yw_rightinformation.parcelUnitId
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public Integer getParcelunitid() {
        return parcelunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.parcelUnitId
     *
     * @param parcelunitid the value for yw_rightinformation.parcelUnitId
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setParcelunitid(Integer parcelunitid) {
        this.parcelunitid = parcelunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.startingTime
     *
     * @return the value of yw_rightinformation.startingTime
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public Date getStartingtime() {
        return startingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.startingTime
     *
     * @param startingtime the value for yw_rightinformation.startingTime
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setStartingtime(Date startingtime) {
        this.startingtime = startingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.endTime
     *
     * @return the value of yw_rightinformation.endTime
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.endTime
     *
     * @param endtime the value for yw_rightinformation.endTime
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.obtainPrice
     *
     * @return the value of yw_rightinformation.obtainPrice
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public String getObtainprice() {
        return obtainprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.obtainPrice
     *
     * @param obtainprice the value for yw_rightinformation.obtainPrice
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setObtainprice(String obtainprice) {
        this.obtainprice = obtainprice == null ? null : obtainprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.landUseRights
     *
     * @return the value of yw_rightinformation.landUseRights
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public String getLanduserights() {
        return landuserights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.landUseRights
     *
     * @param landuserights the value for yw_rightinformation.landUseRights
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setLanduserights(String landuserights) {
        this.landuserights = landuserights == null ? null : landuserights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.certificateBoardId
     *
     * @return the value of yw_rightinformation.certificateBoardId
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public Integer getCertificateboardid() {
        return certificateboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.certificateBoardId
     *
     * @param certificateboardid the value for yw_rightinformation.certificateBoardId
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setCertificateboardid(Integer certificateboardid) {
        this.certificateboardid = certificateboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.characteristicMethodId
     *
     * @return the value of yw_rightinformation.characteristicMethodId
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public Integer getCharacteristicmethodid() {
        return characteristicmethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.characteristicMethodId
     *
     * @param characteristicmethodid the value for yw_rightinformation.characteristicMethodId
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setCharacteristicmethodid(Integer characteristicmethodid) {
        this.characteristicmethodid = characteristicmethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.registrationReason
     *
     * @return the value of yw_rightinformation.registrationReason
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public String getRegistrationreason() {
        return registrationreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.registrationReason
     *
     * @param registrationreason the value for yw_rightinformation.registrationReason
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setRegistrationreason(String registrationreason) {
        this.registrationreason = registrationreason == null ? null : registrationreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightinformation.excursus
     *
     * @return the value of yw_rightinformation.excursus
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public String getExcursus() {
        return excursus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightinformation.excursus
     *
     * @param excursus the value for yw_rightinformation.excursus
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    public void setExcursus(String excursus) {
        this.excursus = excursus == null ? null : excursus.trim();
    }

	public String getWarrantnumber() {
		return warrantnumber;
	}

	public void setWarrantnumber(String warrantnumber) {
		this.warrantnumber = warrantnumber;
	}

	public String getCommonwayname() {
		return commonwayname;
	}

	public void setCommonwayname(String commonwayname) {
		this.commonwayname = commonwayname;
	}

	public String getSit() {
		return sit;
	}

	public void setSit(String sit) {
		this.sit = sit;
	}

	public String getRealrstateunitnumber() {
		return realrstateunitnumber;
	}

	public void setRealrstateunitnumber(String realrstateunitnumber) {
		this.realrstateunitnumber = realrstateunitnumber;
	}

	public String getTypeofrightname() {
		return typeofrightname;
	}

	public void setTypeofrightname(String typeofrightname) {
		this.typeofrightname = typeofrightname;
	}

	public String getProcessclassificationname() {
		return processclassificationname;
	}

	public void setProcessclassificationname(String processclassificationname) {
		this.processclassificationname = processclassificationname;
	}

	public String getUsename() {
		return usename;
	}

	public void setUsename(String usename) {
		this.usename = usename;
	}

	public String getParcelarea() {
		return parcelarea;
	}

	public void setParcelarea(String parcelarea) {
		this.parcelarea = parcelarea;
	}

	public String getUserightarea() {
		return userightarea;
	}

	public void setUserightarea(String userightarea) {
		this.userightarea = userightarea;
	}

	public String getHighbuildinglimit() {
		return highbuildinglimit;
	}

	public void setHighbuildinglimit(String highbuildinglimit) {
		this.highbuildinglimit = highbuildinglimit;
	}

	public String getBuildingdensity() {
		return buildingdensity;
	}

	public void setBuildingdensity(String buildingdensity) {
		this.buildingdensity = buildingdensity;
	}

	public String getPlotratio() {
		return plotratio;
	}

	public void setPlotratio(String plotratio) {
		this.plotratio = plotratio;
	}

	public String getParcelconditioncode() {
		return parcelconditioncode;
	}

	public void setParcelconditioncode(String parcelconditioncode) {
		this.parcelconditioncode = parcelconditioncode;
	}

	public String getMapnumber() {
		return mapnumber;
	}

	public void setMapnumber(String mapnumber) {
		this.mapnumber = mapnumber;
	}

	public Integer getBoxofficeid() {
		return boxofficeid;
	}

	public void setBoxofficeid(Integer boxofficeid) {
		this.boxofficeid = boxofficeid;
	}

	public String getZsbhnumber() {
		return zsbhnumber;
	}

	public void setZsbhnumber(String zsbhnumber) {
		this.zsbhnumber = zsbhnumber;
	}

	public String getIdentifier() {
		return identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getParcelcode() {
		return parcelcode;
	}

	public void setParcelcode(String parcelcode) {
		this.parcelcode = parcelcode;
	}

	public String getCertificateboardname() {
		return certificateboardname;
	}

	public void setCertificateboardname(String certificateboardname) {
		this.certificateboardname = certificateboardname;
	}

	public String getCharacteristicmethodname() {
		return characteristicmethodname;
	}

	public void setCharacteristicmethodname(String characteristicmethodname) {
		this.characteristicmethodname = characteristicmethodname;
	}

	
    
    
}