package com.renjun.po;

public class bs_CertificateBoard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_certificateboard.certificateBoardId
     *
     * @mbggenerated Sun Nov 27 20:12:19 CST 2016
     */
    private Integer certificateboardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_certificateboard.certificateBoardName
     *
     * @mbggenerated Sun Nov 27 20:12:19 CST 2016
     */
    private String certificateboardname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_certificateboard
     *
     * @mbggenerated Sun Nov 27 20:12:19 CST 2016
     */
    public bs_CertificateBoard(Integer certificateboardid, String certificateboardname) {
        this.certificateboardid = certificateboardid;
        this.certificateboardname = certificateboardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_certificateboard
     *
     * @mbggenerated Sun Nov 27 20:12:19 CST 2016
     */
    public bs_CertificateBoard() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_certificateboard.certificateBoardId
     *
     * @return the value of bs_certificateboard.certificateBoardId
     *
     * @mbggenerated Sun Nov 27 20:12:19 CST 2016
     */
    public Integer getCertificateboardid() {
        return certificateboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_certificateboard.certificateBoardId
     *
     * @param certificateboardid the value for bs_certificateboard.certificateBoardId
     *
     * @mbggenerated Sun Nov 27 20:12:19 CST 2016
     */
    public void setCertificateboardid(Integer certificateboardid) {
        this.certificateboardid = certificateboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_certificateboard.certificateBoardName
     *
     * @return the value of bs_certificateboard.certificateBoardName
     *
     * @mbggenerated Sun Nov 27 20:12:19 CST 2016
     */
    public String getCertificateboardname() {
        return certificateboardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_certificateboard.certificateBoardName
     *
     * @param certificateboardname the value for bs_certificateboard.certificateBoardName
     *
     * @mbggenerated Sun Nov 27 20:12:19 CST 2016
     */
    public void setCertificateboardname(String certificateboardname) {
        this.certificateboardname = certificateboardname == null ? null : certificateboardname.trim();
    }
}