package com.renjun.po;

public class bs_CharacteristicMethod {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_characteristicmethod.characteristicMethodId
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    private Integer characteristicmethodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_characteristicmethod.characteristicMethodName
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    private String characteristicmethodname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_characteristicmethod
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    public bs_CharacteristicMethod(Integer characteristicmethodid, String characteristicmethodname) {
        this.characteristicmethodid = characteristicmethodid;
        this.characteristicmethodname = characteristicmethodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_characteristicmethod
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    public bs_CharacteristicMethod() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_characteristicmethod.characteristicMethodId
     *
     * @return the value of bs_characteristicmethod.characteristicMethodId
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    public Integer getCharacteristicmethodid() {
        return characteristicmethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_characteristicmethod.characteristicMethodId
     *
     * @param characteristicmethodid the value for bs_characteristicmethod.characteristicMethodId
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    public void setCharacteristicmethodid(Integer characteristicmethodid) {
        this.characteristicmethodid = characteristicmethodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_characteristicmethod.characteristicMethodName
     *
     * @return the value of bs_characteristicmethod.characteristicMethodName
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    public String getCharacteristicmethodname() {
        return characteristicmethodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_characteristicmethod.characteristicMethodName
     *
     * @param characteristicmethodname the value for bs_characteristicmethod.characteristicMethodName
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    public void setCharacteristicmethodname(String characteristicmethodname) {
        this.characteristicmethodname = characteristicmethodname == null ? null : characteristicmethodname.trim();
    }
}