package com.renjun.po;

public class bs_Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_country.countryId
     *
     * @mbggenerated Fri Nov 18 09:37:05 CST 2016
     */
    private Integer countryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_country.countryName
     *
     * @mbggenerated Fri Nov 18 09:37:05 CST 2016
     */
    private String countryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_country
     *
     * @mbggenerated Fri Nov 18 09:37:05 CST 2016
     */
    public bs_Country(Integer countryid, String countryname) {
        this.countryid = countryid;
        this.countryname = countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_country
     *
     * @mbggenerated Fri Nov 18 09:37:05 CST 2016
     */
    public bs_Country() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_country.countryId
     *
     * @return the value of bs_country.countryId
     *
     * @mbggenerated Fri Nov 18 09:37:05 CST 2016
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_country.countryId
     *
     * @param countryid the value for bs_country.countryId
     *
     * @mbggenerated Fri Nov 18 09:37:05 CST 2016
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_country.countryName
     *
     * @return the value of bs_country.countryName
     *
     * @mbggenerated Fri Nov 18 09:37:05 CST 2016
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_country.countryName
     *
     * @param countryname the value for bs_country.countryName
     *
     * @mbggenerated Fri Nov 18 09:37:05 CST 2016
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname == null ? null : countryname.trim();
    }
}