package com.renjun.po;

public class bs_OpinionTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_opiniontemplate.opinionTemplateId
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    private Integer opiniontemplateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_opiniontemplate.opinionTemplateName
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    private String opiniontemplatename;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_opiniontemplate
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    public bs_OpinionTemplate(Integer opiniontemplateid, String opiniontemplatename) {
        this.opiniontemplateid = opiniontemplateid;
        this.opiniontemplatename = opiniontemplatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_opiniontemplate
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    public bs_OpinionTemplate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_opiniontemplate.opinionTemplateId
     *
     * @return the value of bs_opiniontemplate.opinionTemplateId
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    public Integer getOpiniontemplateid() {
        return opiniontemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_opiniontemplate.opinionTemplateId
     *
     * @param opiniontemplateid the value for bs_opiniontemplate.opinionTemplateId
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    public void setOpiniontemplateid(Integer opiniontemplateid) {
        this.opiniontemplateid = opiniontemplateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_opiniontemplate.opinionTemplateName
     *
     * @return the value of bs_opiniontemplate.opinionTemplateName
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    public String getOpiniontemplatename() {
        return opiniontemplatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_opiniontemplate.opinionTemplateName
     *
     * @param opiniontemplatename the value for bs_opiniontemplate.opinionTemplateName
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    public void setOpiniontemplatename(String opiniontemplatename) {
        this.opiniontemplatename = opiniontemplatename == null ? null : opiniontemplatename.trim();
    }
}