package com.renjun.po;

public class bs_Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_province.provinceId
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_province.countryId
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    private Integer countryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_province.provinceName
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    private String provincename;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    public bs_Province(Integer provinceid, Integer countryid, String provincename) {
        this.provinceid = provinceid;
        this.countryid = countryid;
        this.provincename = provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    public bs_Province() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_province.provinceId
     *
     * @return the value of bs_province.provinceId
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_province.provinceId
     *
     * @param provinceid the value for bs_province.provinceId
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_province.countryId
     *
     * @return the value of bs_province.countryId
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_province.countryId
     *
     * @param countryid the value for bs_province.countryId
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_province.provinceName
     *
     * @return the value of bs_province.provinceName
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_province.provinceName
     *
     * @param provincename the value for bs_province.provinceName
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename == null ? null : provincename.trim();
    }
}