package com.renjun.po;

public class bs_Sex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_sex.sexId
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    private Integer sexid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_sex.sexName
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    private String sexname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_sex
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    public bs_Sex(Integer sexid, String sexname) {
        this.sexid = sexid;
        this.sexname = sexname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_sex
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    public bs_Sex() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_sex.sexId
     *
     * @return the value of bs_sex.sexId
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    public Integer getSexid() {
        return sexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_sex.sexId
     *
     * @param sexid the value for bs_sex.sexId
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    public void setSexid(Integer sexid) {
        this.sexid = sexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_sex.sexName
     *
     * @return the value of bs_sex.sexName
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    public String getSexname() {
        return sexname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_sex.sexName
     *
     * @param sexname the value for bs_sex.sexName
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    public void setSexname(String sexname) {
        this.sexname = sexname == null ? null : sexname.trim();
    }
}