package com.renjun.po;

import java.util.Date;

public class yw_FsBoxOffice {
 
    private Integer fsboxofficeid;


    private Integer boxofficeid;

    
    private Integer userid;

   
    private Integer statusid;

   
    private Date receivingtime;

   
    private String cutOffTime;

    private String overrule;
    private String overrulereason;
    private String send;
  
    public Integer getFsboxofficeid() {
        return fsboxofficeid;
    }

   
    public void setFsboxofficeid(Integer fsboxofficeid) {
        this.fsboxofficeid = fsboxofficeid;
    }

  
    public Integer getBoxofficeid() {
        return boxofficeid;
    }

    public void setBoxofficeid(Integer boxofficeid) {
        this.boxofficeid = boxofficeid;
    }

   
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_fsboxoffice.userId
     *
     * @param userid the value for yw_fsboxoffice.userId
     *
     * @mbggenerated Wed Dec 07 09:47:23 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_fsboxoffice.statusId
     *
     * @return the value of yw_fsboxoffice.statusId
     *
     * @mbggenerated Wed Dec 07 09:47:23 CST 2016
     */
    public Integer getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_fsboxoffice.statusId
     *
     * @param statusid the value for yw_fsboxoffice.statusId
     *
     * @mbggenerated Wed Dec 07 09:47:23 CST 2016
     */
    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

	public Date getReceivingtime() {
		return receivingtime;
	}

	public void setReceivingtime(Date receivingtime) {
		this.receivingtime = receivingtime;
	}

	public String getCutOffTime() {
		return cutOffTime;
	}

	public void setCutOffTime(String cutOffTime) {
		this.cutOffTime = cutOffTime;
	}


	public String getOverrule() {
		return overrule;
	}


	public void setOverrule(String overrule) {
		this.overrule = overrule;
	}


	public String getOverrulereason() {
		return overrulereason;
	}
	public void setOverrulereason(String overrulereason) {
		this.overrulereason = overrulereason;
	}

	public String getSend() {
		return send;
	}
	public void setSend(String send) {
		this.send = send;
	}
}