package com.renjun.po;

public class yw_RightPersonInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_rightpersoninformation.rightpersoninformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    private Integer rightpersoninformationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_rightpersoninformation.rightInformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    private Integer rightinformationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_rightpersoninformation.applicantId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    private Integer applicantid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_rightpersoninformation
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public yw_RightPersonInformation(Integer rightpersoninformationid, Integer rightinformationid, Integer applicantid) {
        this.rightpersoninformationid = rightpersoninformationid;
        this.rightinformationid = rightinformationid;
        this.applicantid = applicantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_rightpersoninformation
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public yw_RightPersonInformation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightpersoninformation.rightpersoninformationId
     *
     * @return the value of yw_rightpersoninformation.rightpersoninformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public Integer getRightpersoninformationid() {
        return rightpersoninformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightpersoninformation.rightpersoninformationId
     *
     * @param rightpersoninformationid the value for yw_rightpersoninformation.rightpersoninformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public void setRightpersoninformationid(Integer rightpersoninformationid) {
        this.rightpersoninformationid = rightpersoninformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightpersoninformation.rightInformationId
     *
     * @return the value of yw_rightpersoninformation.rightInformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public Integer getRightinformationid() {
        return rightinformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightpersoninformation.rightInformationId
     *
     * @param rightinformationid the value for yw_rightpersoninformation.rightInformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public void setRightinformationid(Integer rightinformationid) {
        this.rightinformationid = rightinformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightpersoninformation.applicantId
     *
     * @return the value of yw_rightpersoninformation.applicantId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public Integer getApplicantid() {
        return applicantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightpersoninformation.applicantId
     *
     * @param applicantid the value for yw_rightpersoninformation.applicantId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public void setApplicantid(Integer applicantid) {
        this.applicantid = applicantid;
    }
}