package com.renjun.po;

public class bs_IdCardType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_idcardtype.idCardTypeId
     *
     * @mbggenerated Thu Nov 17 21:26:05 CST 2016
     */
    private Integer idcardtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_idcardtype.idCardTypeName
     *
     * @mbggenerated Thu Nov 17 21:26:05 CST 2016
     */
    private String idcardtypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_idcardtype
     *
     * @mbggenerated Thu Nov 17 21:26:05 CST 2016
     */
    public bs_IdCardType(Integer idcardtypeid, String idcardtypename) {
        this.idcardtypeid = idcardtypeid;
        this.idcardtypename = idcardtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_idcardtype
     *
     * @mbggenerated Thu Nov 17 21:26:05 CST 2016
     */
    public bs_IdCardType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_idcardtype.idCardTypeId
     *
     * @return the value of bs_idcardtype.idCardTypeId
     *
     * @mbggenerated Thu Nov 17 21:26:05 CST 2016
     */
    public Integer getIdcardtypeid() {
        return idcardtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_idcardtype.idCardTypeId
     *
     * @param idcardtypeid the value for bs_idcardtype.idCardTypeId
     *
     * @mbggenerated Thu Nov 17 21:26:05 CST 2016
     */
    public void setIdcardtypeid(Integer idcardtypeid) {
        this.idcardtypeid = idcardtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_idcardtype.idCardTypeName
     *
     * @return the value of bs_idcardtype.idCardTypeName
     *
     * @mbggenerated Thu Nov 17 21:26:05 CST 2016
     */
    public String getIdcardtypename() {
        return idcardtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_idcardtype.idCardTypeName
     *
     * @param idcardtypename the value for bs_idcardtype.idCardTypeName
     *
     * @mbggenerated Thu Nov 17 21:26:05 CST 2016
     */
    public void setIdcardtypename(String idcardtypename) {
        this.idcardtypename = idcardtypename == null ? null : idcardtypename.trim();
    }
}