package com.renjun.po;

public class bs_OwnedIndustry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_ownedindustry.ownedIndustryId
     *
     * @mbggenerated Fri Nov 18 09:38:34 CST 2016
     */
    private Integer ownedindustryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_ownedindustry.ownedIndustryName
     *
     * @mbggenerated Fri Nov 18 09:38:34 CST 2016
     */
    private String ownedindustryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_ownedindustry
     *
     * @mbggenerated Fri Nov 18 09:38:34 CST 2016
     */
    public bs_OwnedIndustry(Integer ownedindustryid, String ownedindustryname) {
        this.ownedindustryid = ownedindustryid;
        this.ownedindustryname = ownedindustryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_ownedindustry
     *
     * @mbggenerated Fri Nov 18 09:38:34 CST 2016
     */
    public bs_OwnedIndustry() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_ownedindustry.ownedIndustryId
     *
     * @return the value of bs_ownedindustry.ownedIndustryId
     *
     * @mbggenerated Fri Nov 18 09:38:34 CST 2016
     */
    public Integer getOwnedindustryid() {
        return ownedindustryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_ownedindustry.ownedIndustryId
     *
     * @param ownedindustryid the value for bs_ownedindustry.ownedIndustryId
     *
     * @mbggenerated Fri Nov 18 09:38:34 CST 2016
     */
    public void setOwnedindustryid(Integer ownedindustryid) {
        this.ownedindustryid = ownedindustryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_ownedindustry.ownedIndustryName
     *
     * @return the value of bs_ownedindustry.ownedIndustryName
     *
     * @mbggenerated Fri Nov 18 09:38:34 CST 2016
     */
    public String getOwnedindustryname() {
        return ownedindustryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_ownedindustry.ownedIndustryName
     *
     * @param ownedindustryname the value for bs_ownedindustry.ownedIndustryName
     *
     * @mbggenerated Fri Nov 18 09:38:34 CST 2016
     */
    public void setOwnedindustryname(String ownedindustryname) {
        this.ownedindustryname = ownedindustryname == null ? null : ownedindustryname.trim();
    }
}