package com.renjun.po;

public class bs_ProcessClassification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_processclassification.processClassificationId
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    private Integer processclassificationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_processclassification.processClassificationName
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    private String processclassificationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_processclassification.typeOfRightId
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    private Integer typeofrightid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_processclassification
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    public bs_ProcessClassification(Integer processclassificationid, String processclassificationname, Integer typeofrightid) {
        this.processclassificationid = processclassificationid;
        this.processclassificationname = processclassificationname;
        this.typeofrightid = typeofrightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_processclassification
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    public bs_ProcessClassification() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_processclassification.processClassificationId
     *
     * @return the value of bs_processclassification.processClassificationId
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    public Integer getProcessclassificationid() {
        return processclassificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_processclassification.processClassificationId
     *
     * @param processclassificationid the value for bs_processclassification.processClassificationId
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    public void setProcessclassificationid(Integer processclassificationid) {
        this.processclassificationid = processclassificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_processclassification.processClassificationName
     *
     * @return the value of bs_processclassification.processClassificationName
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    public String getProcessclassificationname() {
        return processclassificationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_processclassification.processClassificationName
     *
     * @param processclassificationname the value for bs_processclassification.processClassificationName
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    public void setProcessclassificationname(String processclassificationname) {
        this.processclassificationname = processclassificationname == null ? null : processclassificationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_processclassification.typeOfRightId
     *
     * @return the value of bs_processclassification.typeOfRightId
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    public Integer getTypeofrightid() {
        return typeofrightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_processclassification.typeOfRightId
     *
     * @param typeofrightid the value for bs_processclassification.typeOfRightId
     *
     * @mbggenerated Tue Nov 08 15:21:11 CST 2016
     */
    public void setTypeofrightid(Integer typeofrightid) {
        this.typeofrightid = typeofrightid;
    }
}