package com.renjun.po;

public class bs_RegisterType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_registertype.registerTypeId
     *
     * @mbggenerated Tue Nov 08 15:08:52 CST 2016
     */
    private Integer registertypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_registertype.registerTypeName
     *
     * @mbggenerated Tue Nov 08 15:08:52 CST 2016
     */
    private String registertypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_registertype
     *
     * @mbggenerated Tue Nov 08 15:08:52 CST 2016
     */
    public bs_RegisterType(Integer registertypeid, String registertypename) {
        this.registertypeid = registertypeid;
        this.registertypename = registertypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_registertype
     *
     * @mbggenerated Tue Nov 08 15:08:52 CST 2016
     */
    public bs_RegisterType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_registertype.registerTypeId
     *
     * @return the value of bs_registertype.registerTypeId
     *
     * @mbggenerated Tue Nov 08 15:08:52 CST 2016
     */
    public Integer getRegistertypeid() {
        return registertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_registertype.registerTypeId
     *
     * @param registertypeid the value for bs_registertype.registerTypeId
     *
     * @mbggenerated Tue Nov 08 15:08:52 CST 2016
     */
    public void setRegistertypeid(Integer registertypeid) {
        this.registertypeid = registertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_registertype.registerTypeName
     *
     * @return the value of bs_registertype.registerTypeName
     *
     * @mbggenerated Tue Nov 08 15:08:52 CST 2016
     */
    public String getRegistertypename() {
        return registertypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_registertype.registerTypeName
     *
     * @param registertypename the value for bs_registertype.registerTypeName
     *
     * @mbggenerated Tue Nov 08 15:08:52 CST 2016
     */
    public void setRegistertypename(String registertypename) {
        this.registertypename = registertypename == null ? null : registertypename.trim();
    }
}