package com.renjun.po;

import java.util.Date;

public class yw_BoxOffice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.boxOfficeId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private Integer boxofficeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.registerTypeId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    
    private String identifier;
    private Integer statusid; 
    private Integer registertypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.typeOfRightId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private Integer typeofrightid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.processClassificationId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private Integer processclassificationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.entryName
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private String entryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.UrgencyLevel
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private String urgencylevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.ProjectNotes
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private String projectnotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.userid
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.managementActivitiesId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private Integer managementactivitiesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.receivingTime
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private Date receivingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_boxoffice.cut-offTime
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    private String cutOfftime;

    private String overrule;
    private String overrulereason;
    
    
    public Integer getBoxofficeid() {
        return boxofficeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.boxOfficeId
     *
     * @param boxofficeid the value for yw_boxoffice.boxOfficeId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setBoxofficeid(Integer boxofficeid) {
        this.boxofficeid = boxofficeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.registerTypeId
     *
     * @return the value of yw_boxoffice.registerTypeId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public Integer getRegistertypeid() {
        return registertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.registerTypeId
     *
     * @param registertypeid the value for yw_boxoffice.registerTypeId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setRegistertypeid(Integer registertypeid) {
        this.registertypeid = registertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.typeOfRightId
     *
     * @return the value of yw_boxoffice.typeOfRightId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public Integer getTypeofrightid() {
        return typeofrightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.typeOfRightId
     *
     * @param typeofrightid the value for yw_boxoffice.typeOfRightId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setTypeofrightid(Integer typeofrightid) {
        this.typeofrightid = typeofrightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.processClassificationId
     *
     * @return the value of yw_boxoffice.processClassificationId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public Integer getProcessclassificationid() {
        return processclassificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.processClassificationId
     *
     * @param processclassificationid the value for yw_boxoffice.processClassificationId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setProcessclassificationid(Integer processclassificationid) {
        this.processclassificationid = processclassificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.entryName
     *
     * @return the value of yw_boxoffice.entryName
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public String getEntryname() {
        return entryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.entryName
     *
     * @param entryname the value for yw_boxoffice.entryName
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setEntryname(String entryname) {
        this.entryname = entryname == null ? null : entryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.UrgencyLevel
     *
     * @return the value of yw_boxoffice.UrgencyLevel
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public String getUrgencylevel() {
        return urgencylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.UrgencyLevel
     *
     * @param urgencylevel the value for yw_boxoffice.UrgencyLevel
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setUrgencylevel(String urgencylevel) {
        this.urgencylevel = urgencylevel == null ? null : urgencylevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.ProjectNotes
     *
     * @return the value of yw_boxoffice.ProjectNotes
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public String getProjectnotes() {
        return projectnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.ProjectNotes
     *
     * @param projectnotes the value for yw_boxoffice.ProjectNotes
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setProjectnotes(String projectnotes) {
        this.projectnotes = projectnotes == null ? null : projectnotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.userid
     *
     * @return the value of yw_boxoffice.userid
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.userid
     *
     * @param userid the value for yw_boxoffice.userid
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.managementActivitiesId
     *
     * @return the value of yw_boxoffice.managementActivitiesId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public Integer getManagementactivitiesid() {
        return managementactivitiesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.managementActivitiesId
     *
     * @param managementactivitiesid the value for yw_boxoffice.managementActivitiesId
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setManagementactivitiesid(Integer managementactivitiesid) {
        this.managementactivitiesid = managementactivitiesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.receivingTime
     *
     * @return the value of yw_boxoffice.receivingTime
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public Date getReceivingtime() {
        return receivingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_boxoffice.receivingTime
     *
     * @param receivingtime the value for yw_boxoffice.receivingTime
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
    public void setReceivingtime(Date receivingtime) {
        this.receivingtime = receivingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_boxoffice.cut-offTime
     *
     * @return the value of yw_boxoffice.cut-offTime
     *
     * @mbggenerated Wed Nov 09 11:29:20 CST 2016
     */
  

	public String getIdentifier() {
		return identifier;
	}

	public String getCutOfftime() {
		return cutOfftime;
	}

	public void setCutOfftime(String cutOfftime) {
		this.cutOfftime = cutOfftime;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public Integer getStatusid() {
		return statusid;
	}

	public void setStatusid(Integer statusid) {
		this.statusid = statusid;
	}

	public String getOverrule() {
		return overrule;
	}

	public void setOverrule(String overrule) {
		this.overrule = overrule;
	}

	public String getOverrulereason() {
		return overrulereason;
	}

	public void setOverrulereason(String overrulereason) {
		this.overrulereason = overrulereason;
	}
    
    
}