package com.renjun.po;

import java.util.Date;

public class yw_FirstOpiniont {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yw_firstopiniont.firstOpiniontId
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	private Integer firstopiniontid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yw_firstopiniont.firstOpiniontName
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	private String firstopiniontname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column yw_firstopiniont.boxOfficeId
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	  private String jsonresult;
	  private Date createtime;
	public String getJsonresult() {
		return jsonresult;
	}

	public void setJsonresult(String jsonresult) {
		this.jsonresult = jsonresult;
	}

	private Integer boxofficeid;

	private String username;
	
	
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getFirstopiniontid() {
		return firstopiniontid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yw_firstopiniont.firstOpiniontId
	 * @param firstopiniontid  the value for yw_firstopiniont.firstOpiniontId
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	public void setFirstopiniontid(Integer firstopiniontid) {
		this.firstopiniontid = firstopiniontid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yw_firstopiniont.firstOpiniontName
	 * @return  the value of yw_firstopiniont.firstOpiniontName
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	public String getFirstopiniontname() {
		return firstopiniontname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yw_firstopiniont.firstOpiniontName
	 * @param firstopiniontname  the value for yw_firstopiniont.firstOpiniontName
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	public void setFirstopiniontname(String firstopiniontname) {
		this.firstopiniontname = firstopiniontname == null ? null
				: firstopiniontname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column yw_firstopiniont.boxOfficeId
	 * @return  the value of yw_firstopiniont.boxOfficeId
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	public Integer getBoxofficeid() {
		return boxofficeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column yw_firstopiniont.boxOfficeId
	 * @param boxofficeid  the value for yw_firstopiniont.boxOfficeId
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	public void setBoxofficeid(Integer boxofficeid) {
		this.boxofficeid = boxofficeid;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	
	
	
}