package com.renjun.vo;

public class yw_Applicant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.applicantId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer applicantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.applicantName
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String applicantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.sexId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer sexid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.applicationForHumanId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer applicationforhumanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.applicantTypeId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer applicanttypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.idCardTypeId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer idcardtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.IdCardNumber
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String idcardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.phoneNumber
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.commonWayId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer commonwayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.address
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.legalRepresentative
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String legalrepresentative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.legalPhone
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String legalphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.countryId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer countryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.provinceId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.ownedIndustryId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private Integer ownedindustryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.postalcode
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.workUnit
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String workunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.e-mail
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.areaOfRight
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String areaofright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.proportionOfRights
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String proportionofrights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.licenceIssuingAuthority
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String licenceissuingauthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.agency
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String agency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.nameOfAgent
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String nameofagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yw_applicant.agentTelephone
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    private String agenttelephone;

   //新增字段
    private String applicationforhumanname;
    private String idcardtypename;
    private String commonwayname;
    private String rownum;
    private int parcelunitid;
    
    public String getRownum() {
		return rownum;
	}

	public void setRownum(String rownum) {
		this.rownum = rownum;
	}

	public String getApplicationforhumanname() {
		return applicationforhumanname;
	}

	public void setApplicationforhumanname(String applicationforhumanname) {
		this.applicationforhumanname = applicationforhumanname;
	}

	public String getIdcardtypename() {
		return idcardtypename;
	}

	public void setIdcardtypename(String idcardtypename) {
		this.idcardtypename = idcardtypename;
	}

	public String getCommonwayname() {
		return commonwayname;
	}

	public void setCommonwayname(String commonwayname) {
		this.commonwayname = commonwayname;
	}

	public Integer getApplicantid() {
        return applicantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.applicantId
     *
     * @param applicantid the value for yw_applicant.applicantId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setApplicantid(Integer applicantid) {
        this.applicantid = applicantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.applicantName
     *
     * @return the value of yw_applicant.applicantName
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getApplicantname() {
        return applicantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.applicantName
     *
     * @param applicantname the value for yw_applicant.applicantName
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setApplicantname(String applicantname) {
        this.applicantname = applicantname == null ? null : applicantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.sexId
     *
     * @return the value of yw_applicant.sexId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public Integer getSexid() {
        return sexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.sexId
     *
     * @param sexid the value for yw_applicant.sexId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setSexid(Integer sexid) {
        this.sexid = sexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.applicationForHumanId
     *
     * @return the value of yw_applicant.applicationForHumanId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public Integer getApplicationforhumanid() {
        return applicationforhumanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.applicationForHumanId
     *
     * @param applicationforhumanid the value for yw_applicant.applicationForHumanId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setApplicationforhumanid(Integer applicationforhumanid) {
        this.applicationforhumanid = applicationforhumanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.applicantTypeId
     *
     * @return the value of yw_applicant.applicantTypeId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public Integer getApplicanttypeid() {
        return applicanttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.applicantTypeId
     *
     * @param applicanttypeid the value for yw_applicant.applicantTypeId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setApplicanttypeid(Integer applicanttypeid) {
        this.applicanttypeid = applicanttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.idCardTypeId
     *
     * @return the value of yw_applicant.idCardTypeId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public Integer getIdcardtypeid() {
        return idcardtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.idCardTypeId
     *
     * @param idcardtypeid the value for yw_applicant.idCardTypeId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setIdcardtypeid(Integer idcardtypeid) {
        this.idcardtypeid = idcardtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.IdCardNumber
     *
     * @return the value of yw_applicant.IdCardNumber
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getIdcardnumber() {
        return idcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.IdCardNumber
     *
     * @param idcardnumber the value for yw_applicant.IdCardNumber
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setIdcardnumber(String idcardnumber) {
        this.idcardnumber = idcardnumber == null ? null : idcardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.phoneNumber
     *
     * @return the value of yw_applicant.phoneNumber
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.phoneNumber
     *
     * @param phonenumber the value for yw_applicant.phoneNumber
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.commonWayId
     *
     * @return the value of yw_applicant.commonWayId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public Integer getCommonwayid() {
        return commonwayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.commonWayId
     *
     * @param commonwayid the value for yw_applicant.commonWayId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setCommonwayid(Integer commonwayid) {
        this.commonwayid = commonwayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.address
     *
     * @return the value of yw_applicant.address
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.address
     *
     * @param address the value for yw_applicant.address
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.legalRepresentative
     *
     * @return the value of yw_applicant.legalRepresentative
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getLegalrepresentative() {
        return legalrepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.legalRepresentative
     *
     * @param legalrepresentative the value for yw_applicant.legalRepresentative
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setLegalrepresentative(String legalrepresentative) {
        this.legalrepresentative = legalrepresentative == null ? null : legalrepresentative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.legalPhone
     *
     * @return the value of yw_applicant.legalPhone
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getLegalphone() {
        return legalphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.legalPhone
     *
     * @param legalphone the value for yw_applicant.legalPhone
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setLegalphone(String legalphone) {
        this.legalphone = legalphone == null ? null : legalphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.countryId
     *
     * @return the value of yw_applicant.countryId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.countryId
     *
     * @param countryid the value for yw_applicant.countryId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.provinceId
     *
     * @return the value of yw_applicant.provinceId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.provinceId
     *
     * @param provinceid the value for yw_applicant.provinceId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.ownedIndustryId
     *
     * @return the value of yw_applicant.ownedIndustryId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public Integer getOwnedindustryid() {
        return ownedindustryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.ownedIndustryId
     *
     * @param ownedindustryid the value for yw_applicant.ownedIndustryId
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setOwnedindustryid(Integer ownedindustryid) {
        this.ownedindustryid = ownedindustryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.postalcode
     *
     * @return the value of yw_applicant.postalcode
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.postalcode
     *
     * @param postalcode the value for yw_applicant.postalcode
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.workUnit
     *
     * @return the value of yw_applicant.workUnit
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getWorkunit() {
        return workunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.workUnit
     *
     * @param workunit the value for yw_applicant.workUnit
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setWorkunit(String workunit) {
        this.workunit = workunit == null ? null : workunit.trim();
    }

   
    public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAreaofright() {
        return areaofright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.areaOfRight
     *
     * @param areaofright the value for yw_applicant.areaOfRight
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setAreaofright(String areaofright) {
        this.areaofright = areaofright == null ? null : areaofright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.proportionOfRights
     *
     * @return the value of yw_applicant.proportionOfRights
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getProportionofrights() {
        return proportionofrights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.proportionOfRights
     *
     * @param proportionofrights the value for yw_applicant.proportionOfRights
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setProportionofrights(String proportionofrights) {
        this.proportionofrights = proportionofrights == null ? null : proportionofrights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.licenceIssuingAuthority
     *
     * @return the value of yw_applicant.licenceIssuingAuthority
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getLicenceissuingauthority() {
        return licenceissuingauthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.licenceIssuingAuthority
     *
     * @param licenceissuingauthority the value for yw_applicant.licenceIssuingAuthority
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setLicenceissuingauthority(String licenceissuingauthority) {
        this.licenceissuingauthority = licenceissuingauthority == null ? null : licenceissuingauthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.agency
     *
     * @return the value of yw_applicant.agency
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.agency
     *
     * @param agency the value for yw_applicant.agency
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setAgency(String agency) {
        this.agency = agency == null ? null : agency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.nameOfAgent
     *
     * @return the value of yw_applicant.nameOfAgent
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getNameofagent() {
        return nameofagent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.nameOfAgent
     *
     * @param nameofagent the value for yw_applicant.nameOfAgent
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setNameofagent(String nameofagent) {
        this.nameofagent = nameofagent == null ? null : nameofagent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_applicant.agentTelephone
     *
     * @return the value of yw_applicant.agentTelephone
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public String getAgenttelephone() {
        return agenttelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_applicant.agentTelephone
     *
     * @param agenttelephone the value for yw_applicant.agentTelephone
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    public void setAgenttelephone(String agenttelephone) {
        this.agenttelephone = agenttelephone == null ? null : agenttelephone.trim();
    }

	public int getParcelunitid() {
		return parcelunitid;
	}

	public void setParcelunitid(int parcelunitid) {
		this.parcelunitid = parcelunitid;
	}
    
    
}