package com.renjun.vo;

public class yw_RightPersonInformation {
  
    private Integer rightpersoninformationid;

    private Integer rightinformationid;

   
    private Integer applicantid;

    //新增字段
    private int boxofficeid;
    private String applicantname;
         
    public Integer getRightpersoninformationid() {
        return rightpersoninformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightpersoninformation.rightpersoninformationId
     *
     * @param rightpersoninformationid the value for yw_rightpersoninformation.rightpersoninformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public void setRightpersoninformationid(Integer rightpersoninformationid) {
        this.rightpersoninformationid = rightpersoninformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightpersoninformation.rightInformationId
     *
     * @return the value of yw_rightpersoninformation.rightInformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public Integer getRightinformationid() {
        return rightinformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightpersoninformation.rightInformationId
     *
     * @param rightinformationid the value for yw_rightpersoninformation.rightInformationId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public void setRightinformationid(Integer rightinformationid) {
        this.rightinformationid = rightinformationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yw_rightpersoninformation.applicantId
     *
     * @return the value of yw_rightpersoninformation.applicantId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public Integer getApplicantid() {
        return applicantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yw_rightpersoninformation.applicantId
     *
     * @param applicantid the value for yw_rightpersoninformation.applicantId
     *
     * @mbggenerated Mon Nov 28 08:45:18 CST 2016
     */
    public void setApplicantid(Integer applicantid) {
        this.applicantid = applicantid;
    }

	public int getBoxofficeid() {
		return boxofficeid;
	}

	public void setBoxofficeid(int boxofficeid) {
		this.boxofficeid = boxofficeid;
	}

	public String getApplicantname() {
		return applicantname;
	}

	public void setApplicantname(String applicantname) {
		this.applicantname = applicantname;
	}
    
    
}