package com.renjun.dao;

import java.util.List;

import com.renjun.po.bs_ApplicationForHuman;

public interface bs_ApplicationForHumanMapper {
    
	
	//查询申请人类别
	public List<bs_ApplicationForHuman> selectApplicationforhuman();
	
    int deleteByPrimaryKey(Integer applicationforhumanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicationforhuman
     *
     * @mbggenerated Thu Nov 17 21:16:35 CST 2016
     */
    int insert(bs_ApplicationForHuman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicationforhuman
     *
     * @mbggenerated Thu Nov 17 21:16:35 CST 2016
     */
    int insertSelective(bs_ApplicationForHuman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicationforhuman
     *
     * @mbggenerated Thu Nov 17 21:16:35 CST 2016
     */
    bs_ApplicationForHuman selectByPrimaryKey(Integer applicationforhumanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicationforhuman
     *
     * @mbggenerated Thu Nov 17 21:16:35 CST 2016
     */
    int updateByPrimaryKeySelective(bs_ApplicationForHuman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicationforhuman
     *
     * @mbggenerated Thu Nov 17 21:16:35 CST 2016
     */
    int updateByPrimaryKey(bs_ApplicationForHuman record);
}