package com.renjun.dao;

import java.util.List;

import com.renjun.po.bs_CharacteristicMethod;

public interface bs_CharacteristicMethodMapper {
   //查询特征方式
	public List<bs_CharacteristicMethod> selectCharacteristicMethod();
    int deleteByPrimaryKey(Integer characteristicmethodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_characteristicmethod
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    int insert(bs_CharacteristicMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_characteristicmethod
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    int insertSelective(bs_CharacteristicMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_characteristicmethod
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    bs_CharacteristicMethod selectByPrimaryKey(Integer characteristicmethodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_characteristicmethod
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    int updateByPrimaryKeySelective(bs_CharacteristicMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_characteristicmethod
     *
     * @mbggenerated Sun Nov 27 20:13:07 CST 2016
     */
    int updateByPrimaryKey(bs_CharacteristicMethod record);
}