package com.renjun.dao;

import java.util.List;

import com.renjun.po.bs_ReasonTemplate;

public interface bs_ReasonTemplateMapper {
  
	//查询原因模板
	public List<bs_ReasonTemplate> selectReasonTemplate();
	//新增原因模板
	public boolean insertReasonTemplate(bs_ReasonTemplate bs_ReasonTemplate);
	//修改原因模板
	public boolean updateReasonTemplate(bs_ReasonTemplate bs_ReasonTemplate);
	//删除原因模板
	public boolean deleteReasonTemplate(int reasontemplateid);
	//模糊查询原因模板
	public List<bs_ReasonTemplate> selectReasonTemplateMh(String reasontemplatename);
    int deleteByPrimaryKey(Integer reasontemplateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_reasontemplate
     *
     * @mbggenerated Mon Dec 05 15:34:21 CST 2016
     */
    int insert(bs_ReasonTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_reasontemplate
     *
     * @mbggenerated Mon Dec 05 15:34:21 CST 2016
     */
    int insertSelective(bs_ReasonTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_reasontemplate
     *
     * @mbggenerated Mon Dec 05 15:34:21 CST 2016
     */
    bs_ReasonTemplate selectByPrimaryKey(Integer reasontemplateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_reasontemplate
     *
     * @mbggenerated Mon Dec 05 15:34:21 CST 2016
     */
    int updateByPrimaryKeySelective(bs_ReasonTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_reasontemplate
     *
     * @mbggenerated Mon Dec 05 15:34:21 CST 2016
     */
    int updateByPrimaryKey(bs_ReasonTemplate record);
}