package com.renjun.dao;

import java.util.List;

import com.renjun.po.yw_Applicant;

public interface yw_ApplicantMapper {
   //新增申请人
	public boolean insertApplicant(yw_Applicant yw_Applicant);
	
	//修改申请人
	public boolean updateApplicant(yw_Applicant yw_Applicant);
	
	//删除申请人
	public boolean deleteApplicant(int applicantid);
	//查询申请人
   public List<yw_Applicant> selectApplicant();
    //模糊查询申请人
    public List<yw_Applicant> selectMhApplicant(String content);
    int deleteByPrimaryKey(Integer applicantid);

    //查询权利人
    public List<com.renjun.vo.yw_Applicant> selectRightApplicant();
    
    public List<com.renjun.vo.yw_Applicant> selectRightApplicantByParcelunitid(int parcelunitid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_applicant
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    int insert(yw_Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_applicant
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    int insertSelective(yw_Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_applicant
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    yw_Applicant selectByPrimaryKey(Integer applicantid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_applicant
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    int updateByPrimaryKeySelective(yw_Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_applicant
     *
     * @mbggenerated Fri Nov 18 11:05:33 CST 2016
     */
    int updateByPrimaryKey(yw_Applicant record);
}