package com.renjun.dao;

import com.renjun.po.yw_FirstOpiniont;

public interface yw_FirstOpiniontMapper {

	//新增初审
	public boolean insertFirstOpiniont(yw_FirstOpiniont yw_FirstOpiniont);
	//查看上一级审核意见
	public yw_FirstOpiniont selectFirstOpiniont(int boxofficeid);
	//修改初审
	public boolean updateFirstopiniont(yw_FirstOpiniont yw_FirstOpiniont);
	int deleteByPrimaryKey(Integer firstopiniontid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yw_firstopiniont
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	int insert(yw_FirstOpiniont record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yw_firstopiniont
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	int insertSelective(yw_FirstOpiniont record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yw_firstopiniont
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	yw_FirstOpiniont selectByPrimaryKey(Integer firstopiniontid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yw_firstopiniont
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	int updateByPrimaryKeySelective(yw_FirstOpiniont record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table yw_firstopiniont
	 * @mbggenerated  Sun Dec 04 08:10:46 CST 2016
	 */
	int updateByPrimaryKey(yw_FirstOpiniont record);
}