package com.renjun.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.renjun.po.yw_RightInformation;

public interface yw_RightInformationMapper {
   
	//保存权利信息
	public boolean insertRightInformation(yw_RightInformation yw_RightInformation);
	//查询证书信息
	public com.renjun.vo.yw_RightInformation selectDocumentInformation(int rightinformationid);
	//查询登簿坐落
	public List<com.renjun.vo.yw_RightInformation> selectRegisterBookSit(int boxofficeid);
    int deleteByPrimaryKey(Integer rightinformationid);
    //查询收费权利信息
    public com.renjun.vo.yw_RightInformation selectSfRightInformation(int boxofficeid);
    //根据办箱id查询收费信息单元 
    public List<com.renjun.vo.yw_RightInformation> selectRightInformationByBoxOfficeId(int boxofficeid);
    //根据办箱Id查询宗地单元坐落
    public com.renjun.vo.yw_RightInformation selectBdcByBoxOfficeId(int parcelunitid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_rightinformation
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    int insert(yw_RightInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_rightinformation
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    int insertSelective(yw_RightInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_rightinformation
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    yw_RightInformation selectByPrimaryKey(Integer rightinformationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_rightinformation
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    int updateByPrimaryKeySelective(yw_RightInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yw_rightinformation
     *
     * @mbggenerated Mon Nov 28 08:44:42 CST 2016
     */
    int updateByPrimaryKey(yw_RightInformation record);
}