package com.renjun.dao;

import java.util.List;

import com.renjun.po.bs_ApplicantType;

public interface bs_ApplicantTypeMapper {
   
	//查询申请人类型
	public List<bs_ApplicantType> selectApplicanttype();
    int deleteByPrimaryKey(Integer applicanttypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicanttype
     *
     * @mbggenerated Thu Nov 17 21:20:00 CST 2016
     */
    int insert(bs_ApplicantType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicanttype
     *
     * @mbggenerated Thu Nov 17 21:20:00 CST 2016
     */
    int insertSelective(bs_ApplicantType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicanttype
     *
     * @mbggenerated Thu Nov 17 21:20:00 CST 2016
     */
    bs_ApplicantType selectByPrimaryKey(Integer applicanttypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicanttype
     *
     * @mbggenerated Thu Nov 17 21:20:00 CST 2016
     */
    int updateByPrimaryKeySelective(bs_ApplicantType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_applicanttype
     *
     * @mbggenerated Thu Nov 17 21:20:00 CST 2016
     */
    int updateByPrimaryKey(bs_ApplicantType record);
}