package com.renjun.dao;

import java.util.List;

import com.renjun.po.bs_OpinionTemplate;

public interface bs_OpinionTemplateMapper {
  
	//查询意见模板
	public List<bs_OpinionTemplate> selectOpinionTemplate();
	//保存意见模板
	public boolean insertOpinionTemplate(bs_OpinionTemplate bs_OpinionTemplate);
	//修改意见模板
	public boolean updateOpinionTemplate(bs_OpinionTemplate bs_OpinionTemplate);
	//模糊查询
	public List<bs_OpinionTemplate> selectOpinionTemplateMh(String opiniontemplatename);
	//删除意见模板
	public boolean deleteOpinionTemplate(int opiniontemplateid);
    int deleteByPrimaryKey(Integer opiniontemplateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_opiniontemplate
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    int insert(bs_OpinionTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_opiniontemplate
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    int insertSelective(bs_OpinionTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_opiniontemplate
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    bs_OpinionTemplate selectByPrimaryKey(Integer opiniontemplateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_opiniontemplate
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    int updateByPrimaryKeySelective(bs_OpinionTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_opiniontemplate
     *
     * @mbggenerated Wed Nov 30 11:26:18 CST 2016
     */
    int updateByPrimaryKey(bs_OpinionTemplate record);
}