package com.renjun.dao;

import java.util.List;

import com.renjun.po.bs_Province;

public interface bs_ProvinceMapper {
    //查询省份
	public List<bs_Province> selectProvince(int countryid);
    int deleteByPrimaryKey(Integer provinceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    int insert(bs_Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    int insertSelective(bs_Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    bs_Province selectByPrimaryKey(Integer provinceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    int updateByPrimaryKeySelective(bs_Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_province
     *
     * @mbggenerated Fri Nov 18 09:37:37 CST 2016
     */
    int updateByPrimaryKey(bs_Province record);
}