package com.renjun.dao;

import java.util.List;

import com.renjun.po.bs_Sex;

public interface bs_SexMapper {
 
	//查询性别
	public List<bs_Sex> selectSex();
	
    int deleteByPrimaryKey(Integer sexid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_sex
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    int insert(bs_Sex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_sex
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    int insertSelective(bs_Sex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_sex
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    bs_Sex selectByPrimaryKey(Integer sexid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_sex
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    int updateByPrimaryKeySelective(bs_Sex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_sex
     *
     * @mbggenerated Thu Nov 17 21:12:35 CST 2016
     */
    int updateByPrimaryKey(bs_Sex record);
}