package com.renjun.dao;

import com.renjun.po.IdentifierNumber;

public interface IdentifierNumberMapper {
    
	public IdentifierNumber selectidentifiernumber(int identifiernumberid);
	public boolean updateIdentifiernumber(IdentifierNumber identifierNumber);
	
    int deleteByPrimaryKey(Integer identifiernumberid);

    
    int insert(IdentifierNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifiernumber
     *
     * @mbggenerated Fri Nov 11 21:43:13 CST 2016
     */
    int insertSelective(IdentifierNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifiernumber
     *
     * @mbggenerated Fri Nov 11 21:43:13 CST 2016
     */
    IdentifierNumber selectByPrimaryKey(Integer identifiernumberid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifiernumber
     *
     * @mbggenerated Fri Nov 11 21:43:13 CST 2016
     */
    int updateByPrimaryKeySelective(IdentifierNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identifiernumber
     *
     * @mbggenerated Fri Nov 11 21:43:13 CST 2016
     */
    int updateByPrimaryKey(IdentifierNumber record);
}