package com.renjun.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.renjun.po.User;

public interface UserMapper {
  
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Nov 08 15:01:25 CST 2016
	 */
	int insert(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Nov 08 15:01:25 CST 2016
	 */
	int insertSelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Nov 08 15:01:25 CST 2016
	 */
	User selectByPrimaryKey(Integer userid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Nov 08 15:01:25 CST 2016
	 */
	int updateByPrimaryKeySelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Nov 08 15:01:25 CST 2016
	 */
	int updateByPrimaryKey(User record);
	public com.renjun.vo.User getName(@Param("username") String username);
    public com.renjun.vo.User getUserByName(@Param("username") String username,@Param("password") String password);
    public List<com.renjun.vo.User> selectUserByQuartersTypeId(int quarterstypeid);
    //查询用户
	public List<com.renjun.vo.User> selectUser(@Param("pageStart") int pageStart,@Param("pageSize") int pageSize);
    int deleteByPrimaryKey(Integer userid);
    public int lines();
    //新增用户
    public boolean insertUser(User user);
    //根据用户查询用户Id
    public User selectUserByUserId(int userid);
    //根据员工Id修改员工信息、
    public boolean updateUser(User user);
    //根据用户Id修改用户密码
    public boolean updatePassword(User user);
}